# Jekyll configuration
# 
# 
title: Welcome to Cheng Huang's HomePage
tagline: Security&Privacy.
owner: Cheng Huang
copyright: 2016 created by Cheng Huang


# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: 


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
comments: true

gems: [jekyll-paginate]
permalink: /:year/:month/:title
paginate: 5
paginate_path: "news/page:num"

highlighter: pygments
markdown: kramdown

url: http://chenghuang.info

exclude: ['README.md']

