# Jekyll configuration
# 
# 
title: Cheng's Blog
tagline: Security&Privacy.
owner: Cheng Huang
copyright: Cheng Huang 2015


# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: 


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
comments: true

permalink: /:year/:month/:title
paginate: 5

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

url: http://endercheng.github.io

exclude: ['README.md']

